# The config file

# Dataset
dataset_name: synthetic_netflix

# Hyperparameters
batch_size : 1
n_epoch : 10
rate_training_validation : 0.5
nb_iterations_rnn : 10
out_channels : 32
learning_rate : 1e-3
p_order_row : 5
p_order_col : 5

# Logging 
log_each : 1
log_level : INFO # DEBUG, INFO, WARNING, ERROR