# for the clusters
nb_users: 150
nb_movies: 200

# The cluster
nb_neighbour_users: 8
nb_neighbour_movies: 13

# The graph
proba_within_users: 0.6
proba_within_movies: 0.6

# The data
nb_ranked: 7
mean_good_ranked: 4
mean_bad_ranked: 2
variance_ranking: 1


# Hyperparameters
batch_size : 1
rank : 10
n_epoch : 10000
rate_test : 0.1
rate_training: 0.5
nb_iterations_rnn : 10
out_channels : 32
learning_rate : 1e-3
p_order : 5
gamma : 1e-7

# The config file

# Logging 
log_each : 10
log_level : INFO # DEBUG, INFO, WARNING, ERRO
tensorboard_dir : "runs"

# Reproductibility
seed : 42
